(() => {
  const SIZE=8, KEEP={x:3,y:3}, STEP=1.58;
  const TYPES={farm:{name:'Granja',icon:'🌾',cost:30,label:'ORO +2',desc:'Genera 2 de oro cada 2 segundos.',income:2},mine:{name:'Mina',icon:'⛏️',cost:45,label:'ORO +5',desc:'Genera 5 de oro cada 3 segundos.',income:5},tower:{name:'Torre',icon:'🏹',cost:55,label:'12 daño',desc:'Dispara al invasor más cercano en un radio de 3 casillas.',damage:12,range:3,cooldown:900},barracks:{name:'Cuartel',icon:'⚔️',cost:70,label:'18 daño',desc:'Sus guardias frenan invasores a corta distancia.',damage:18,range:1.55,cooldown:650},wall:{name:'Muralla',icon:'🧱',cost:18,label:'80 vida',desc:'Bloquea el paso y compra tiempo.',hp:80}};
  const DIFFICULTY={relaxed:{hp:.78,amount:.78},normal:{hp:1,amount:1},hard:{hp:1.35,amount:1.25}};
  let state,selected='tower',muted=false,audioCtx,lastFrame=0,raf,scene,camera,renderer,raycaster,mouse,tiles=[],projectiles=[],threeLoopStarted=false;
  const $=id=>document.getElementById(id), el={field:$('battlefield'),gold:$('gold'),health:$('health'),time:$('time'),wave:$('wave'),waveHint:$('waveHint'),threat:$('threatFill'),threatText:$('threatText'),selectedName:$('selectedName'),selectedDesc:$('selectedDesc'),bar:$('buildBar'),toast:$('toast'),ability:$('ability'),abilityText:$('abilityText')};
  const material=color=>new THREE.MeshLambertMaterial({color});
  const cellPos=(x,y)=>new THREE.Vector3((x-(SIZE-1)/2)*STEP,0,(y-(SIZE-1)/2)*STEP);
  function fresh(){return{running:false,difficulty:'normal',time:60,gold:120,totalGold:120,health:100,wave:0,kills:0,buildings:[],enemies:[],nextId:1,nextWaveAt:0,abilityReady:true,lastIncome:0};}
  function init3D(){
    if(!renderer){renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.field.append(renderer.domElement);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',onBoardClick);window.addEventListener('resize',resize);}
    scene=new THREE.Scene();scene.fog=new THREE.Fog(0x253833,10,22);scene.background=new THREE.Color(0x263b38);camera=new THREE.PerspectiveCamera(43,1,.1,100);camera.position.set(8.8,10.8,12.3);camera.lookAt(0,0,0);tiles=[];projectiles=[];
    scene.add(new THREE.HemisphereLight(0xd9e9c1,0x1d2d28,1.7));const sun=new THREE.DirectionalLight(0xffdeb0,1.65);sun.position.set(-7,12,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(26,26),material(0x2d493c));ground.rotation.x=-Math.PI/2;ground.position.y=-.17;ground.receiveShadow=true;scene.add(ground);
    for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const color=(x+y)%2?0x78985c:0x688b55;const tile=new THREE.Mesh(new THREE.BoxGeometry(1.48,.18,1.48),material(color));tile.position.copy(cellPos(x,y));tile.position.y=-.03;tile.receiveShadow=true;tile.userData={x,y,tile:true};scene.add(tile);tiles.push(tile);}
    const ring=new THREE.Mesh(new THREE.TorusGeometry(1.2,.035,8,32),new THREE.MeshBasicMaterial({color:0xe7bd5c}));ring.rotation.x=Math.PI/2;ring.position.copy(cellPos(KEEP.x,KEEP.y));ring.position.y=.1;scene.add(ring);const keep=makeModel('keep');keep.position.copy(cellPos(KEEP.x,KEEP.y));scene.add(keep);resize();if(!threeLoopStarted){threeLoopStarted=true;animate3D()}
  }
  function resize(){if(!renderer||!el.field.clientWidth)return;const w=el.field.clientWidth,h=el.field.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
  function makeModel(type){
    const g=new THREE.Group(),add=(geo,mat,x=0,y=0,z=0)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};
    if(type==='keep'){const stone=material(0xc0b18e),roof=material(0x75483c);add(new THREE.BoxGeometry(1.15,1.25,1.05),stone,0,.62,0);[[-.45,-.4],[.45,-.4],[-.45,.4],[.45,.4]].forEach(([x,z])=>{add(new THREE.CylinderGeometry(.18,.22,.65,5),stone,x,1.1,z);add(new THREE.ConeGeometry(.25,.36,5),roof,x,1.59,z)});add(new THREE.ConeGeometry(.9,.55,4),roof,0,1.52,0);return g}
    const wood=material(0x865437),straw=material(0xe5b94d),stone=material(0x8f9a91),iron=material(0x4a5350),red=material(0xa94038);
    if(type==='farm'){add(new THREE.BoxGeometry(1.12,.16,1.12),material(0x8b6239),0,.1,0);for(let i=-.35;i<=.35;i+=.35)for(let z=-.35;z<=.35;z+=.35)add(new THREE.ConeGeometry(.09,.55,5),material(0x9fbc45),i,.35,z);add(new THREE.BoxGeometry(.35,.3,.35),wood,.38,.25,.34);add(new THREE.ConeGeometry(.35,.26,4),straw,.38,.53,.34)}
    if(type==='mine'){add(new THREE.CylinderGeometry(.64,.7,.25,7),stone,0,.14,0);add(new THREE.CylinderGeometry(.42,.47,.26,7),iron,0,.29,.08);add(new THREE.BoxGeometry(.64,.15,.18),wood,0,.55,.25);add(new THREE.CylinderGeometry(.06,.06,.75,5),wood,-.25,.62,.25);add(new THREE.CylinderGeometry(.06,.06,.75,5),wood,.25,.62,.25)}
    if(type==='tower'){add(new THREE.CylinderGeometry(.34,.48,1.45,7),stone,0,.72,0);add(new THREE.CylinderGeometry(.48,.48,.14,7),stone,0,1.48,0);add(new THREE.ConeGeometry(.6,.48,7),red,0,1.78,0);add(new THREE.BoxGeometry(.75,.08,.08),wood,0,1.42,0)}
    if(type==='barracks'){add(new THREE.BoxGeometry(1.12,.65,.95),red,0,.36,0);add(new THREE.ConeGeometry(.88,.55,4),material(0x4e3940),0,.92,0);add(new THREE.BoxGeometry(.25,.38,.03),wood,0,.27,.49)}
    if(type==='wall'){add(new THREE.BoxGeometry(1.35,.78,.3),stone,0,.38,0);for(let x=-.48;x<=.48;x+=.32)add(new THREE.BoxGeometry(.18,.16,.34),stone,x,.82,0)}
    return g
  }
  function makeEnemy(elite){const g=new THREE.Group(),skin=material(elite?0xb74a36:0x9b3b39),dark=material(0x3d2427);const body=new THREE.Mesh(new THREE.CylinderGeometry(.2,.28,.55,6),skin);body.position.y=.42;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.DodecahedronGeometry(.22,0),skin);head.position.y=.82;head.castShadow=true;g.add(head);const horn=new THREE.Mesh(new THREE.ConeGeometry(.1,.25,4),dark);horn.position.set(0,1.08,0);g.add(horn);if(elite){const club=new THREE.Mesh(new THREE.BoxGeometry(.08,.55,.08),dark);club.position.set(.3,.6,0);club.rotation.z=.5;g.add(club)}const bg=new THREE.Mesh(new THREE.BoxGeometry(.52,.05,.04),material(0x4e2020));bg.position.y=1.22;g.add(bg);const bar=new THREE.Mesh(new THREE.BoxGeometry(.5,.04,.05),material(0xf07a55));bar.position.set(-.01,1.22,.03);g.add(bar);g.userData.bar=bar;return g}
  function onBoardClick(e){if(!state?.running)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(tiles,false)[0];if(hit)buildAt(hit.object.userData.x,hit.object.userData.y)}
  function animate3D(){if(scene)renderer.render(scene,camera);requestAnimationFrame(animate3D)}
  function buildButtons(){el.bar.innerHTML='';Object.entries(TYPES).forEach(([type,t],i)=>{const b=document.createElement('button');b.className=`build-btn ${selected===type?'active':''}`;b.dataset.type=type;b.innerHTML=`<span class="build-icon">${t.icon}</span><span><b>${i+1}. ${t.name}</b><small>${t.label}</small></span><span class="cost">✦${t.cost}</span>`;b.onclick=()=>choose(type);el.bar.append(b)});choose(selected)}
  function choose(type){selected=type;const t=TYPES[type];el.selectedName.textContent=`${t.icon} ${t.name} · ${t.cost} oro`;el.selectedDesc.textContent=t.desc;document.querySelectorAll('.build-btn').forEach(b=>b.classList.toggle('active',b.dataset.type===type));sound('select')}
  function buildAt(x,y){if(x===KEEP.x&&y===KEEP.y)return toast('El Bastión no puede moverse');const t=TYPES[selected];if(state.buildings.some(b=>b.x===x&&b.y===y))return toast('Ya hay una estructura aquí');if(state.gold<t.cost)return toast('Necesitas más oro');state.gold-=t.cost;const mesh=makeModel(selected);mesh.position.copy(cellPos(x,y));scene.add(mesh);state.buildings.push({...t,type:selected,x,y,hp:t.hp||1,lastShot:0,mesh});updateHud();toast(`${t.name} construido`);sound('build')}
  function spawnWave(){state.wave++;const d=DIFFICULTY[state.difficulty],n=Math.ceil((3+state.wave*1.75)*d.amount);state.waveHint.textContent=`${n} invasores cruzan la frontera`;for(let i=0;i<n;i++)setTimeout(()=>spawnEnemy(state.wave,d),i*440);toast(`⚔ OLEADA ${state.wave}: ¡el ejército de ceniza!`);sound('wave')}
  function spawnEnemy(wave,d){if(!state.running)return;const edge=Math.floor(Math.random()*4);let x,y;if(edge===0){x=Math.floor(Math.random()*SIZE);y=0}else if(edge===1){x=SIZE-1;y=Math.floor(Math.random()*SIZE)}else if(edge===2){x=Math.floor(Math.random()*SIZE);y=SIZE-1}else{x=0;y=Math.floor(Math.random()*SIZE)};const elite=wave>=3&&Math.random()<.18,hp=Math.round((25+wave*10+(elite?42:0))*d.hp),mesh=makeEnemy(elite);mesh.position.copy(cellPos(x,y));scene.add(mesh);state.enemies.push({id:state.nextId++,x,y,hp,maxHp:hp,damage:elite?12:7,elite,mesh,lastMove:0,lastAttack:0})}
  function positionEnemy(e){e.mesh.position.copy(cellPos(e.x,e.y));e.mesh.userData.bar.scale.x=Math.max(.01,e.hp/e.maxHp)}function isBlocked(x,y){return state.buildings.find(b=>b.type==='wall'&&b.x===x&&b.y===y)}
  function updateEnemies(now){state.enemies.slice().forEach(e=>{e.mesh.rotation.y+=.045;if(now-e.lastMove<=470)return;e.lastMove=now;const dx=KEEP.x-e.x,dy=KEEP.y-e.y,options=[];if(dx)options.push({x:e.x+Math.sign(dx),y:e.y});if(dy)options.push({x:e.x,y:e.y+Math.sign(dy)});options.sort(()=>Math.random()-.48);let moved=false;for(const n of options){const wall=isBlocked(n.x,n.y);if(wall){if(now-e.lastAttack>700){e.lastAttack=now;wall.hp-=e.damage;wall.mesh.scale.y=.78+Math.max(0,wall.hp/80)*.22;if(wall.hp<=0){scene.remove(wall.mesh);state.buildings.splice(state.buildings.indexOf(wall),1);toast('¡Una muralla ha caído!');sound('break')}}break}else{e.x=n.x;e.y=n.y;moved=true;break}}if(!moved&&e.x===KEEP.x&&e.y===KEEP.y&&now-e.lastAttack>700){e.lastAttack=now;damageKeep(e.damage)}positionEnemy(e)})}
  function damageKeep(n){state.health=Math.max(0,state.health-n);sound('hurt');updateHud();if(state.health<=0)end(false)}
  function fight(now){state.buildings.forEach(b=>{if(!b.damage||now-b.lastShot<b.cooldown)return;const target=state.enemies.filter(e=>Math.hypot(e.x-b.x,e.y-b.y)<=b.range).sort((a,c)=>Math.hypot(a.x-KEEP.x,a.y-KEEP.y)-Math.hypot(c.x-KEEP.x,c.y-KEEP.y))[0];if(!target)return;b.lastShot=now;shoot(b,target);hurtEnemy(target,b.damage)})}
  function shoot(from,to){const orb=new THREE.Mesh(new THREE.SphereGeometry(.09,7,7),new THREE.MeshBasicMaterial({color:0xffe29c}));orb.position.copy(from.mesh.position).add(new THREE.Vector3(0,.8,0));scene.add(orb);projectiles.push({mesh:orb,start:orb.position.clone(),end:to.mesh.position.clone().add(new THREE.Vector3(0,.65,0)),at:performance.now()});sound('shot')}
  function updateProjectiles(now){projectiles.slice().forEach(p=>{const t=Math.min(1,(now-p.at)/190);p.mesh.position.lerpVectors(p.start,p.end,t);if(t===1){scene.remove(p.mesh);projectiles.splice(projectiles.indexOf(p),1)}})}
  function hurtEnemy(e,n){e.hp-=n;positionEnemy(e);if(e.hp<=0){state.kills++;state.gold+=e.elite?15:7;scene.remove(e.mesh);state.enemies.splice(state.enemies.indexOf(e),1);sound('kill');updateHud()}}
  function income(now){if(now-state.lastIncome<1000)return;state.lastIncome=now;const farms=state.buildings.filter(b=>b.type==='farm').length,mines=state.buildings.filter(b=>b.type==='mine').length,gain=(farms&&now%2000<1050?farms*2:0)+(mines&&now%3000<1050?mines*5:0);if(gain){state.gold+=gain;state.totalGold+=gain;toast(`+${gain} oro de tu economía`);updateHud()}}
  function updateHud(){el.gold.textContent=Math.floor(state.gold);el.health.textContent=Math.ceil(state.health);el.time.textContent=Math.max(0,Math.ceil(state.time));el.wave.textContent=`${state.wave} / 6`;const threat=Math.min(100,state.enemies.length*12+state.wave*5);el.threat.style.width=`${threat}%`;el.threatText.textContent=state.enemies.length?`${state.enemies.length} invasores en el mapa`:'En calma';el.ability.disabled=!state.abilityReady;el.abilityText.textContent=state.abilityReady?'¡Lista para usar!':'Recargando...'}
  function tick(now){if(!state.running)return;if(!lastFrame)lastFrame=now;state.time-=(now-lastFrame)/1000;lastFrame=now;if(state.time<=0){state.time=0;updateHud();return end(true)}if(now>=state.nextWaveAt&&state.wave<6){spawnWave();state.nextWaveAt+=9200}income(now);updateEnemies(now);fight(now);updateProjectiles(now);updateHud();raf=requestAnimationFrame(tick)}
  function fury(){if(!state?.running||!state.abilityReady)return;state.abilityReady=false;state.enemies.slice().forEach(e=>hurtEnemy(e,42));toast('☄ ¡La Furia Real incendia las líneas enemigas!');sound('fury');updateHud();setTimeout(()=>{if(state.running){state.abilityReady=true;updateHud()}},14500)}
  function start(){state=fresh();state.difficulty=document.querySelector('.difficulty .active').dataset.difficulty;state.nextWaveAt=performance.now()+3000;init3D();buildButtons();updateHud();$('startModal').classList.add('hidden');lastFrame=0;state.running=true;raf=requestAnimationFrame(tick);sound('start')}
  function end(won){if(!state.running)return;state.running=false;cancelAnimationFrame(raf);$('endModal').classList.remove('hidden');$('resultIcon').textContent=won?'♛':'⚔';$('resultLabel').textContent=won?'EL AMANECER LLEGÓ':'EL BASTIÓN HA CAÍDO';$('resultTitle').textContent=won?'¡El reino resiste!':'La corona se ha quebrado';$('resultCopy').textContent=won?'Has convertido un terreno vacío en una defensa que resistió al ejército de ceniza.':'Las oleadas encontraron una brecha. Equilibra economía, muros y defensa de largo alcance.';$('finalWaves').textContent=state.wave;$('finalKills').textContent=state.kills;$('finalGold').textContent=state.totalGold;const record=+localStorage.getItem('reinos60-record')||0;if(state.kills>record)localStorage.setItem('reinos60-record',state.kills);setRecord();sound(won?'win':'lose')}
  function toast(m){el.toast.textContent=m;el.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove('show'),1700)}function setRecord(){const r=+localStorage.getItem('reinos60-record')||0;$('record').textContent=r?`${r} invasores derrotados`:'Aún no hay leyenda'}
  function sound(type){if(muted)return;try{audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime,map={build:[460,.06,.09],shot:[770,.025,.05],kill:[220,.04,.08],hurt:[110,.07,.13],fury:[130,.13,.35],win:[520,.08,.32],lose:[140,.09,.25],wave:[180,.07,.18],select:[560,.025,.04],start:[380,.05,.12],break:[90,.07,.12]},[f,v,d]=map[type]||[400,.03,.05];o.type=type==='fury'?'sawtooth':'triangle';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(type==='win'?f*1.8:Math.max(60,f*.55),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+d)}catch{}}
  document.querySelectorAll('.difficulty button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.difficulty button').forEach(x=>x.classList.remove('active'));b.classList.add('active');sound('select')});$('start').onclick=start;$('again').onclick=()=>{$('endModal').classList.add('hidden');$('startModal').classList.remove('hidden')};$('ability').onclick=fury;$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'🔇':'🔊'};window.addEventListener('keydown',e=>{if(e.key>='1'&&e.key<='5')choose(Object.keys(TYPES)[+e.key-1]);if(e.code==='Space'){e.preventDefault();fury()}});setRecord();
})();
